### PR TITLE
Added a code to get into 1st level of closure in case of other decorator wrapping func

### PR DESCRIPTION
**Pull request by benoitm974**

### CODE REVIEW

**Comment by benoitm974** [comment]
I'm not sure how to adress the python 2.6 and 3.x unit test error weren't there before ?

**Comment by defnull** [comment]
This is already a feature of the Route context class:
https://github.com/bottlepy/bottle/blob/master/bottle.py#L576

**Comment by defnull** [comment]
Even better: https://github.com/bottlepy/bottle/blob/master/bottle.py#L594
http://bottlepy.org/docs/dev/api.html#bottle.Route.get_callback_args

**Comment by benoitm974** [comment]
Great but it seems there is still a bug as some function have some closure that are not wrapper in this case you need to get the previous func from the recursion. i'll refactor and propose a new pacth then. Thanks anyone for pointing me in this new direction.

**Pull request closed without merging**
